version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/posrgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
